ALTER TABLE bc_node
    ADD COLUMN E_VALUE NUMERIC,
    ADD COLUMN QUANTITY NUMERIC,
    ADD COLUMN PRODUCTION_VOLUME NUMERIC,
    ADD COLUMN SCOPE3 NUMERIC,
    ADD COLUMN TRANSPORTATION_EMISSION NUMERIC;
